[tasks.setup]
description = "Install dependencies"
run = "bundle install"

[tasks.build]
description = "Generate the metrics dashboard"
depends = ["setup"]
run = "bundle exec rake generate"

[tasks.serve]
description = "Serve the dashboard locally on port 8080"
depends = ["setup"]
run = "cd dist && ruby -run -e httpd . -p 8080"