[env]
# Load environment variables from .env file
_.file = ".env"

[tasks.setup]
description = "Install dependencies"
run = [
    "bundle install",
    "npm install"
]

[tasks.build]
description = "Generate the metrics dashboard"
depends = ["setup"]
run = "bundle exec rake generate"

[tasks.serve]
description = "Serve the dashboard locally with HTTP/2 and HTTPS"
depends = ["setup"]
run = "cd dist && caddy file-server --browse --listen :8080"

[tasks.tf-plan]
description = "Plan Terraform infrastructure changes"
run = "cd terraform && terraform plan"

[tasks.tf-apply]
description = "Apply Terraform infrastructure changes"
run = "cd terraform && terraform apply"

[tasks.tf-init]
description = "Initialize Terraform"
run = "cd terraform && terraform init"

[tasks.tf-show]
description = "Show Terraform state"
run = "cd terraform && terraform show"

[tasks.deploy]
description = "Deploy dashboard to Cloudflare Pages"
depends = ["build"]
run = "npx wrangler pages deploy dist --project-name=datanate-dashboard"

[tools]
ruby = "latest"
terraform = "latest"
watchexec = "latest"
